"""
Django settings for NebulaSource project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4&cks=*@*f=80+@*um5l_2u5q=7$!m-1qaztbx83a&1)%i)bnh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Nebula',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NebulaSource.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NebulaSource.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#import mongoengine
#DATABASES = {
#    from pymongo import MongoClient
#client = MongoClient('connection_string')
#db = client['db_name']
#}
import os
from pymongo import MongoClient

#MONGO_DB_NAME = 'NebulaSource'
#MONGO_DB_USER = os.environ.get('adityaseth936')
#MONGO_DB_PASSWORD = os.environ.get('adityaseth0905')
#MONGO_DB_CLUSTER = os.environ.get('nebulasource.ueavgem.mongodb.net')
#MONGO_DB_URI = f"mongodb+srv://{MONGO_DB_USER}:{MONGO_DB_PASSWORD}@{MONGO_DB_CLUSTER}/{MONGO_DB_NAME}?retryWrites=true&w=majority"
#"mongodb+srv://adityaseth936:adityaseth0905@nebulasource.ueavgem.mongodb.net/?retryWrites=true&w=majority&appName=NebulaSource"
#client = MongoClient(MONGO_DB_URI)
#db = client[MONGO_DB_NAME]
#import os
#from pymongo import MongoClient

MONGO_DB_USER = 'adityaseth936'
MONGO_DB_PASSWORD = 'adityaseth0905'
MONGO_DB_CLUSTER = 'nebulasource.ueavgem.mongodb.net'
MONGO_DB_NAME = 'NebulaSourceDB'
MONGO_DB_URI = f"mongodb+srv://{MONGO_DB_USER}:{MONGO_DB_PASSWORD}@{MONGO_DB_CLUSTER}/{MONGO_DB_NAME}?retryWrites=true&w=majority&appName=NebulaSource"

client = MongoClient(MONGO_DB_URI)
db = client[MONGO_DB_NAME]



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Nebula/static'),
]

AUTH_USER_MODEL = 'Nebula.CustomUser'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
